// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLKuYoONwENdZ7nhyiym7Bio_D-6cG04',
    appId: '1:898355390271:web:e5d24dfe74d25c12c9558a',
    messagingSenderId: '898355390271',
    projectId: 'kinideas-firebase',
    authDomain: 'kinideas-firebase.firebaseapp.com',
    databaseURL: 'https://kinideas-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'kinideas-firebase.appspot.com',
    measurementId: 'G-1MB9KP5HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyUalvNlaJqOf59FQ8dIzgZ70JOVymR4',
    appId: '1:898355390271:android:2bf6b659a5d77084c9558a',
    messagingSenderId: '898355390271',
    projectId: 'kinideas-firebase',
    databaseURL: 'https://kinideas-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'kinideas-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fuf6fdzCmBKSaiw2x8fz3XD7eJkHp0w',
    appId: '1:898355390271:ios:1ae2c7fe86e80439c9558a',
    messagingSenderId: '898355390271',
    projectId: 'kinideas-firebase',
    databaseURL: 'https://kinideas-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'kinideas-firebase.appspot.com',
    iosClientId: '898355390271-cgjsfjb43vdsf1a935sbcq58io5trs79.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinMusicAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fuf6fdzCmBKSaiw2x8fz3XD7eJkHp0w',
    appId: '1:898355390271:ios:1ae2c7fe86e80439c9558a',
    messagingSenderId: '898355390271',
    projectId: 'kinideas-firebase',
    databaseURL: 'https://kinideas-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'kinideas-firebase.appspot.com',
    iosClientId: '898355390271-cgjsfjb43vdsf1a935sbcq58io5trs79.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinMusicAuth',
  );
  
}
